version: '3.8'

services:
  user-management:
    image: xpapaya/user-management:dev-5
    ports:
      - "8080:5000"
    networks:
      - web

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - web

networks:
  web:
    name: web